### ISSUE TITLE
pygments missing in requirements.txt

### ISSUE THREAD

**Issue by cb109** [Mani4D46/strawberry-editor#2]
```bash
pip install -r requirements.txt
python start.py
```

```py
Traceback (most recent call last):
  File "start.py", line 3, in <module>
    from src import window
  File "/home/user/projects/strawberry-editor/src/window.py", line 10, in <module>
    from .edit import TextEditor
  File "/home/user/projects/strawberry-editor/src/edit.py", line 7, in <module>
    from pygments.formatters import Terminal256Formatter, TerminalFormatter
ModuleNotFoundError: No module named 'pygments'
```

**Comment by Mani4D46** [comment]
i fix it right now
